"""
Compute PPL and TPR for ByteKGWv6 and KGW from generated CSVs.

Assumes CSVs generated by scripts/generate_clean_v6_kgw.py:
  - hf_generate.csv
  - bytekgw_v6_deltaX.csv
  - kgw_deltaX.csv

Usage:
  TOKENIZERS_PARALLELISM=false /home/star/jf/python/stega/bin/python scripts/analyze_v6_kgw_tpr.py \
    --run_meta outputs/c4_samples_head_200/run_metadata.json \
    --v6_config config/ByteKGWv6.json \
    --kgw_config config/KGW.json \
    --input_dir outputs/v6_vs_kgw_gen \
    --deltas 1,2,3,4,5 \
    --fprs 0.01,0.05,0.1,0.2 \
    --device cuda:0
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from tqdm import tqdm

import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from MarkLLM.watermark.bytekgwV6.token_bytes import TokenByteVocabV6  # type: ignore
from MarkLLM.watermark.bytekgwV6.prf import RobustPartitioner  # type: ignore
from MarkLLM.watermark.bytekgwV6.detector import ByteKGWv6Detector  # type: ignore
from MarkLLM.watermark.kgw.kgw import KGWUtils  # type: ignore


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_meta", required=True)
    ap.add_argument("--v6_config", required=True)
    ap.add_argument("--kgw_config", required=True)
    ap.add_argument("--input_dir", required=True)
    ap.add_argument("--deltas", default="1,2,3,4,5")
    ap.add_argument("--fprs", default="0.01,0.05,0.1,0.2")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--n_clean", type=int, default=None, help="number of clean rows for threshold (default all)")
    ap.add_argument("--n_samples", type=int, default=None, help="number of samples per delta (default all)")
    ap.add_argument("--skip_ppl", action="store_true", help="skip PPL computation to run faster")
    ap.add_argument("--ppl_batch_size", type=int, default=4, help="batch size for PPL computation")
    return ap.parse_args()


def load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _to_bytes(key) -> bytes:
    if isinstance(key, bytes):
        return key
    if isinstance(key, str):
        s = key.strip()
        if s.startswith("0x"):
            try:
                return int(s, 16).to_bytes(16, "little", signed=False)
            except Exception:
                pass
        return s.encode("utf-8")
    try:
        return int(key).to_bytes(16, "little", signed=False)
    except Exception:
        return b"default-key"


def load_model(model_path: str, device: str):
    tok = AutoTokenizer.from_pretrained(model_path)
    mdl = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float16 if device.startswith("cuda") else None,
    ).to(device)
    mdl.eval()
    return tok, mdl


@torch.no_grad()
def batch_perplexity(model, tokenizer, texts: List[str], device: str, batch_size: int) -> List[float]:
    """Compute per-sequence PPL in batches."""
    if model is None or len(texts) == 0:
        return [float("nan")] * len(texts)
    # ensure padding token
    if tokenizer.pad_token_id is None and tokenizer.eos_token_id is not None:
        tokenizer.pad_token = tokenizer.eos_token
    ppl: List[float] = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        encoded = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            add_special_tokens=False,
            return_attention_mask=True,
        ).to(device)
        input_ids = encoded["input_ids"]
        attn = encoded["attention_mask"]
        labels = input_ids.clone()
        labels[attn == 0] = -100
        outputs = model(input_ids=input_ids, attention_mask=attn, labels=labels)
        logits = outputs.logits
        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = labels[..., 1:].contiguous()
        shift_mask = attn[..., 1:].contiguous()
        loss_flat = torch.nn.functional.cross_entropy(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1),
            reduction="none",
        )
        loss_flat = loss_flat.view(shift_labels.size()) * shift_mask
        token_counts = shift_mask.sum(dim=1).clamp(min=1)
        seq_loss = loss_flat.sum(dim=1) / token_counts
        ppl.extend(torch.exp(seq_loss).detach().cpu().tolist())
    return ppl


def conservative_threshold(z: np.ndarray, fpr: float) -> float:
    q = 1.0 - float(fpr)
    return float(np.quantile(z, q, interpolation="linear"))


def build_v6_detector(v6_cfg: Dict[str, Any], tokenizer, device: str) -> ByteKGWv6Detector:
    vocab = TokenByteVocabV6.from_tokenizer(tokenizer, skip_markers=True).to(device)
    partitioner = RobustPartitioner(
        master_key=_to_bytes(v6_cfg.get("hash_key", 15485863)),
        m_bits=int(v6_cfg.get("m_bits", 256)),
        target_anchors=int(v6_cfg.get("target_anchors", 96)),
        k_choices=tuple(v6_cfg.get("k_choices", [4, 5, 6])),
        normalize_whitespace=bool(v6_cfg.get("normalize_whitespace", True)),
    )
    det = ByteKGWv6Detector(
        tokenizer=tokenizer,
        vocab=vocab,
        partitioner=partitioner,
        n_bytes=int(v6_cfg.get("n_bytes", 3)),
        seed_window_chars=int(v6_cfg.get("seed_window_chars", 18)),
        z_threshold=float(v6_cfg.get("z_threshold", 4.0)),
        min_tokens=int(v6_cfg.get("min_tokens", 0)),
        device=device,
        add_special_tokens=bool(v6_cfg.get("add_special_tokens", True)),
    )
    return det


def score_v6(detector: ByteKGWv6Detector, tokenizer, df: pd.DataFrame, model, device: str, compute_ppl: bool, ppl_batch_size: int) -> Tuple[np.ndarray, np.ndarray, List[float]]:
    z_list: List[float] = []
    hit_rates: List[float] = []
    texts: List[str] = []
    for _, row in tqdm(df.iterrows(), total=len(df), desc="V6 detect", leave=False):
        res = detector.detect(row["full_text"], return_dict=True)
        z_list.append(res["z"])
        hit_rates.append(res["green_frac"])
        texts.append(row["full_text"])
    ppl_list = batch_perplexity(model, tokenizer, texts, device, ppl_batch_size) if compute_ppl else [float("nan")] * len(texts)
    return np.array(z_list, dtype=float), np.array(ppl_list, dtype=float), hit_rates


def score_kgw(kgw_utils: KGWUtils, tokenizer, df: pd.DataFrame, cfg: Dict[str, Any], model, device: str, compute_ppl: bool, ppl_batch_size: int) -> Tuple[np.ndarray, np.ndarray, List[float]]:
    z_list: List[float] = []
    hit_rates: List[float] = []
    texts: List[str] = []
    add_special_tokens = bool(cfg.get("add_special_tokens", True))
    prefix_len = int(cfg.get("prefix_length", 4))
    for _, row in tqdm(df.iterrows(), total=len(df), desc="KGW detect", leave=False):
        encoded = tokenizer(row["full_text"], return_tensors="pt", add_special_tokens=add_special_tokens).to(device)
        ids = encoded["input_ids"][0]
        if ids.numel() <= prefix_len:
            z_list.append(float("-inf"))
            hit_rates.append(0.0)
            texts.append(row["full_text"])
            continue
        z_score, flags = kgw_utils.score_sequence(ids)
        z_list.append(z_score)
        hits = sum(1 for f in flags[prefix_len:] if f == 1)
        total = len(flags) - prefix_len
        hit_rates.append(hits / total if total > 0 else 0.0)
        texts.append(row["full_text"])
    ppl_list = batch_perplexity(model, tokenizer, texts, device, ppl_batch_size) if compute_ppl else [float("nan")] * len(texts)
    return np.array(z_list, dtype=float), np.array(ppl_list, dtype=float), hit_rates


def main() -> None:
    args = parse_args()
    run_meta = load_json(args.run_meta)
    v6_cfg = load_json(args.v6_config)
    kgw_cfg = load_json(args.kgw_config)
    deltas = [float(x) for x in args.deltas.split(",") if x.strip()]
    fprs = [float(x) for x in args.fprs.split(",") if x.strip()]

    compute_ppl = not args.skip_ppl

    model_path = run_meta["model"]
    tokenizer, model = load_model(model_path, args.device) if compute_ppl else (AutoTokenizer.from_pretrained(model_path), None)

    # clean
    df_clean = pd.read_csv(Path(args.input_dir) / "hf_generate.csv")
    if args.n_clean:
        df_clean = df_clean.head(args.n_clean)

    # detector
    det = build_v6_detector(v6_cfg, tokenizer, args.device)
    z_clean, ppl_clean, _ = score_v6(det, tokenizer, df_clean, model, args.device, compute_ppl, args.ppl_batch_size)
    thresholds = {fpr: conservative_threshold(z_clean, fpr) for fpr in fprs}
    print(f"Clean z mean={z_clean.mean():.3f} std={z_clean.std():.3f}")

    def _read_delta(prefix: str, delta_val: float) -> pd.DataFrame:
        """Load CSV for a delta, handling both int and float filenames."""
        base = Path(args.input_dir)
        path_int = base / f"{prefix}{int(delta_val)}.csv"
        path_float = base / f"{prefix}{delta_val}.csv"
        if path_int.exists():
            return pd.read_csv(path_int)
        if path_float.exists():
            return pd.read_csv(path_float)
        raise FileNotFoundError(f"Missing CSV for delta={delta_val}: tried {path_int} and {path_float}")

    for delta in deltas:
        df_v6 = _read_delta("bytekgw_v6_delta", delta)
        if args.n_samples:
            df_v6 = df_v6.head(args.n_samples)
        z_v6, ppl_v6, hits_v6 = score_v6(det, tokenizer, df_v6, model, args.device, compute_ppl, args.ppl_batch_size)
        print(f"\n[V6] delta={delta}: z mean={z_v6.mean():.3f} std={z_v6.std():.3f} ppl_mean={ppl_v6.mean():.3f}")
        print("  per-sample hit_rate:", ", ".join(f"{h:.3f}" for h in hits_v6))
        for fpr in fprs:
            thr = thresholds[fpr]
            tpr = float((z_v6 >= thr).mean())
            print(f"  fpr={fpr:.2f} thr={thr:.3f} -> tpr={tpr:.3f}")

    # KGW
    class SimpleKGWConfig:
        def __init__(self, cfg: Dict[str, Any], vocab_size: int, device: str) -> None:
            self.gamma = float(cfg.get("gamma", 0.5))
            self.delta = float(cfg.get("delta", 2.0))
            self.hash_key = int(cfg.get("hash_key", 15485863))
            self.z_threshold = float(cfg.get("z_threshold", 4.0))
            self.prefix_length = int(cfg.get("prefix_length", 4))
            self.f_scheme = cfg.get("f_scheme", "additive")
            self.window_scheme = cfg.get("window_scheme", "left")
            self.vocab_size = int(vocab_size)
            self.device = device

    kgw_config_obj = SimpleKGWConfig(kgw_cfg, vocab_size=len(tokenizer), device=args.device)
    kgw_utils = KGWUtils(kgw_config_obj)

    # KGW clean thresholds
    z_list_clean_kgw, _, _ = score_kgw(kgw_utils, tokenizer, df_clean if args.n_clean is None else df_clean.head(args.n_clean), kgw_cfg, model, args.device, compute_ppl, args.ppl_batch_size)
    thresholds_kgw = {fpr: conservative_threshold(z_list_clean_kgw, fpr) for fpr in fprs}
    print(f"\n[KGW] Clean z mean={z_list_clean_kgw.mean():.3f} std={z_list_clean_kgw.std():.3f}")

    for delta in deltas:
        kgw_config_obj.delta = float(delta)
        df_k = _read_delta("kgw_delta", delta)
        if args.n_samples:
            df_k = df_k.head(args.n_samples)
        z_k, ppl_k, hits_k = score_kgw(kgw_utils, tokenizer, df_k, kgw_cfg, model, args.device, compute_ppl, args.ppl_batch_size)
        print(f"\n[KGW] delta={delta}: z mean={z_k.mean():.3f} std={z_k.std():.3f} ppl_mean={ppl_k.mean():.3f}")
        print("  per-sample hit_rate:", ", ".join(f"{h:.3f}" for h in hits_k))
        for fpr in fprs:
            thr = thresholds_kgw[fpr]
            tpr = float((z_k >= thr).mean())
            print(f"  fpr={fpr:.2f} thr={thr:.3f} -> tpr={tpr:.3f}")
        if 0.1 in fprs:
            thr = thresholds_kgw[0.1]
            tpr = float((z_k >= thr).mean())
            print(f"  [summary] fpr=0.10 thr={thr:.3f} tpr={tpr:.3f}")


if __name__ == "__main__":
    main()
