"""
Measure PRF stability: green-set overlap before vs. after char attack.

For each sample and each continuation token:
  1) Compute fingerprint on clean prefix -> green mask over present first-n IDs.
  2) Compute fingerprint on attacked prefix -> green mask over the same ID set.
  3) Overlap = |G_clean ∩ G_att| / |G_clean| (and IoU).

Summaries: mean overlap / IoU per token and overall.

Assumes input CSV generated by scripts/generate_clean_v6_kgw.py (has prompt_text/full_text).

Example:
  TOKENIZERS_PARALLELISM=false /home/star/jf/python/stega/bin/python scripts/analyze_v6_prf_overlap.py \
    --run_meta outputs/c4_samples_head_200/run_metadata.json \
    --v6_config config/ByteKGWv6.json \
    --input_csv outputs/v6_vs_kgw_gen/bytekgw_v6_delta2.0.csv \
    --attack_ratio 0.02 \
    --n_samples 50 \
    --device cuda:0
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from transformers import AutoTokenizer

import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from MarkLLM.watermark.bytekgwV6.token_bytes import TokenByteVocabV6  # type: ignore
from MarkLLM.watermark.bytekgwV6.prf import RobustPartitioner  # type: ignore


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run_meta", required=True)
    ap.add_argument("--v6_config", required=True)
    ap.add_argument("--input_csv", required=True, help="CSV with prompt_text/full_text")
    ap.add_argument("--n_samples", type=int, default=None, help="limit number of rows")
    ap.add_argument("--attack_ratio", type=float, default=0.02, help="fraction of continuation chars to corrupt")
    ap.add_argument("--attack_seed", type=int, default=0, help="seed for char attack")
    ap.add_argument("--device", default="cpu")
    return ap.parse_args()


def load_json(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def apply_char_attack(text: str, prompt_text: str, ratio: float, *, seed: int = 0) -> str:
    if ratio <= 0.0:
        return text
    import random

    random.seed(seed)
    if text.startswith(prompt_text):
        prefix = prompt_text
        cont = text[len(prompt_text) :]
    else:
        prefix = ""
        cont = text
    chars = list(cont)
    L = len(chars)
    k = max(1, int(L * ratio)) if L > 0 else 0
    idxs = random.sample(range(L), k) if L > 0 else []
    for i in idxs:
        chars[i] = "X"
    return prefix + "".join(chars)


def build_partitioner(v6_cfg: Dict[str, Any]) -> RobustPartitioner:
    return RobustPartitioner(
        master_key=_to_bytes(v6_cfg.get("hash_key", 15485863)),
        m_bits=int(v6_cfg.get("m_bits", 256)),
        target_anchors=int(v6_cfg.get("target_anchors", 96)),
        k_choices=tuple(v6_cfg.get("k_choices", [4, 5, 6])),
        normalize_whitespace=bool(v6_cfg.get("normalize_whitespace", True)),
    )


def _to_bytes(key) -> bytes:
    if isinstance(key, bytes):
        return key
    if isinstance(key, str):
        s = key.strip()
        if s.startswith("0x"):
            try:
                return int(s, 16).to_bytes(16, "little", signed=False)
            except Exception:
                pass
        return s.encode("utf-8")
    try:
        return int(key).to_bytes(16, "little", signed=False)
    except Exception:
        return b"default-key"


class GreenSetHelper:
    """
    Lightweight helper to compute green masks for subsets of first-n IDs.
    """

    def __init__(self, vocab: TokenByteVocabV6, partitioner: RobustPartitioner, n_bytes: int, device: str) -> None:
        self.partitioner = partitioner
        self.device = torch.device(device)
        self.firstn_ids = vocab.first_n_id(self.device, n_bytes)  # [V] int64

        uniq, inv = torch.unique(self.firstn_ids.cpu(), return_inverse=True)
        self._uniq_ids = uniq  # CPU
        self._inv_vocab = inv.to(self.device)

        w_list = []
        tie_list = []
        for uid in uniq.tolist():
            w_bytes = partitioner.token_vector(uid)
            tie = partitioner._tie_bit(uid) if hasattr(partitioner, "_tie_bit") else None
            if tie is None:
                import hmac, hashlib

                tie = hmac.new(partitioner.k_tok, b"tie" + uid.to_bytes(8, "little", signed=False), hashlib.sha256).digest()[0] & 1
            w_list.append(torch.tensor(list(w_bytes), dtype=torch.uint8))
            tie_list.append(tie)
        self._w = torch.stack(w_list, dim=0).to(self.device) if w_list else torch.empty((0, partitioner.m_bytes), dtype=torch.uint8, device=self.device)
        self._tie = torch.tensor(tie_list, dtype=torch.uint8, device=self.device)
        self._lut = torch.tensor([bin(i).count("1") for i in range(256)], dtype=torch.uint8, device=self.device)
        self.half_bits = partitioner.m_bits // 2
        self._id_to_idx: Dict[int, int] = {int(v): i for i, v in enumerate(uniq.tolist())}

    def green_mask_subset(self, fp: bytes, present_firstn: torch.Tensor) -> torch.Tensor:
        """
        fp: fingerprint bytes
        present_firstn: [M] int64 unique first-n ids
        returns: [M] bool on device
        """
        if present_firstn.numel() == 0:
            return torch.empty((0,), device=self.device, dtype=torch.bool)
        idxs = torch.tensor([self._id_to_idx[int(x)] for x in present_firstn.tolist()], device=self.device, dtype=torch.long)
        w = self._w.index_select(0, idxs)  # [M, m_bytes]
        tie_bits = self._tie.index_select(0, idxs)  # [M]
        fp_t = torch.tensor(list(fp), device=self.device, dtype=torch.uint8)  # [m_bytes]
        xor = torch.bitwise_xor(w, fp_t.unsqueeze(0))
        hd = torch.take(self._lut, xor.view(-1).to(torch.long)).view(xor.shape).sum(dim=1)  # [M]
        green = hd < self.half_bits
        tie_mask = hd == self.half_bits
        if tie_mask.any():
            green[tie_mask] = (tie_bits[tie_mask] & 1) == 0
        return green


def main() -> None:
    args = parse_args()
    run_meta = load_json(args.run_meta)
    v6_cfg = load_json(args.v6_config)
    seed_window_chars = int(v6_cfg.get("seed_window_chars", 18))
    n_bytes = int(v6_cfg.get("n_bytes", 3))
    add_special_tokens = bool(v6_cfg.get("add_special_tokens", True))

    tok = AutoTokenizer.from_pretrained(run_meta["model"])
    vocab = TokenByteVocabV6.from_tokenizer(tok, skip_markers=True).to(args.device)
    partitioner = build_partitioner(v6_cfg)
    helper = GreenSetHelper(vocab, partitioner, n_bytes=n_bytes, device=args.device)

    df = pd.read_csv(args.input_csv)
    if args.n_samples:
        df = df.head(args.n_samples)

    overlaps: List[float] = []
    ious: List[float] = []
    per_sample_mean: List[float] = []
    tail_match = 0
    tail_total = 0

    for row_idx, row in tqdm(list(df.iterrows()), desc="Samples"):
        prompt = row.get("prompt_text", "")
        full = row["full_text"]
        attacked = apply_char_attack(full, prompt, args.attack_ratio, seed=args.attack_seed + row_idx)

        # 按字符对齐：逐字符位置截取前缀，再 fingerprint/划分
        prompt_len_chars = len(prompt)
        max_len = min(len(full), len(attacked))

        sample_overlaps: List[float] = []
        sample_ious: List[float] = []

        for t in range(prompt_len_chars, max_len):
            prefix_c = full[:t]
            prefix_a = attacked[:t]
            fp_c = partitioner.fingerprint(prefix_c, seed_window_chars)
            fp_a = partitioner.fingerprint(prefix_a, seed_window_chars)

            # track seed窗口是否一致（用 fingerprint 的同样截断逻辑）
            tail_c = partitioner._last_n_chars(prefix_c, seed_window_chars)  # type: ignore[attr-defined]
            tail_a = partitioner._last_n_chars(prefix_a, seed_window_chars)  # type: ignore[attr-defined]
            tail_match += int(tail_c == tail_a)
            tail_total += 1

            ids_c = tok(prefix_c, return_tensors="pt", add_special_tokens=add_special_tokens)["input_ids"][0].to(args.device)
            ids_a = tok(prefix_a, return_tensors="pt", add_special_tokens=add_special_tokens)["input_ids"][0].to(args.device)
            firstn_c = helper.firstn_ids.index_select(0, ids_c) if ids_c.numel() > 0 else torch.empty((0,), device=args.device, dtype=torch.int64)
            firstn_a = helper.firstn_ids.index_select(0, ids_a) if ids_a.numel() > 0 else torch.empty((0,), device=args.device, dtype=torch.int64)
            present = torch.unique(torch.cat([firstn_c, firstn_a], dim=0))

            g_c = helper.green_mask_subset(fp_c, present)
            g_a = helper.green_mask_subset(fp_a, present)
            inter = (g_c & g_a).sum().item()
            denom = g_c.sum().item()
            union = (g_c | g_a).sum().item()
            overlap = inter / denom if denom > 0 else 0.0
            iou = inter / union if union > 0 else 0.0
            sample_overlaps.append(overlap)
            sample_ious.append(iou)

        if sample_overlaps:
            per_sample_mean.append(float(np.mean(sample_overlaps)))
            overlaps.extend(sample_overlaps)
            ious.extend(sample_ious)

    if overlaps:
        print(f"Mean overlap (|Gc∩Ga|/|Gc|): {np.mean(overlaps):.4f}")
        print(f"Mean IoU (|Gc∩Ga|/|Gc∪Ga|): {np.mean(ious):.4f}")
        print(f"Per-sample overlap mean: mean={np.mean(per_sample_mean):.4f} std={np.std(per_sample_mean):.4f}")
        qs = np.percentile(overlaps, [0, 10, 25, 50, 75, 90, 100])
        print(f"Overlap quantiles: min={qs[0]:.4f} p10={qs[1]:.4f} p25={qs[2]:.4f} p50={qs[3]:.4f} p75={qs[4]:.4f} p90={qs[5]:.4f} max={qs[6]:.4f}")
        if tail_total > 0:
            print(f"Tail window exact match rate (clean vs attack): {tail_match/tail_total:.4f}")
    else:
        print("No tokens processed.")


if __name__ == "__main__":
    main()
